### ISSUE TITLE
Tags are mandatory in announcement and news app

### ISSUE THREAD

**Issue by Monal5031** [iiitv/Odyssy#104]
While adding announcement or news we cannot leave the tags field empty. Is this a bug or it is intended to have a tag for each thing.
cc: @yashLadha

**Comment by yashLadha** [comment]
May be we can set a default tag, or make this field non-empty

**Comment by yashLadha** [comment]
Actually currently i am busy with some other project. So can you send PR for the same. @Monal5031

**Comment by Monal5031** [comment]
Sure, just needed views if it was a bug or not.
