### ISSUE TITLE
Showing localhost as Disallowed host

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/Odyssy#11]
**Problem Statement**

If we are testing application on localhost, and we do a get (or post) request, then Error 400 is returned.

**Solution**

Add localhost and 127.0.0.1 in ALLOWED_HOST list in settings.py

**Comment by singhpratyush** [comment]
This should not happen as on `localhost`, debug mode is on. Are you setting Openshift related env vars?

**Comment by yashLadha** [comment]
We can pass a generic arg like `'*'`. It resolves this issue.

**Comment by Prakash2403** [comment]
> We can pass a generic arg like '*'. It resolves this issue.

@yashLadha Yeah, we could do it for now, but at the end when website will be live, we will have to change it again. 

> This should not happen as on `localhost,` debug mode is on. Are you setting Openshift related env vars?

@singhpratyush I thought they were set automatically. Setting OPENSHIFT_APP_DNS resolves the problem. I think it will be nice to add a section about environment variables in README. Nevertheless, most of us will be testing on our local machine, so I think that mentioning loopback address in ALLOWED_HOSTS is fine. Or at least, we could change the line `os.environ.get('OPENSHIFT_APP_DNS')` to `os.environ.get('OPENSHIFT_APP_DNS', '127.0.0.1')`

**Comment by singhpratyush** [comment]
@Prakash2403: The app check if the env var `OPENSHIFT_PYTHON_IP` and if it exists, it sets the `ON_OPENSHIFT` variable to True (See [this](https://github.com/iiitv/Odyssy/blob/master/wsgi/odyssy/odyssy/settings.py#L24)). The DEBUG variable is set as `!ON_OPENSHIFT` (See [this](https://github.com/iiitv/Odyssy/blob/master/wsgi/odyssy/odyssy/settings.py#L36)), so DEBUG mode is on when not on Openshift, implying that all hosts will be allowed.

I think that this problem should not occur on localhost as the `OPENSHIFT_PYTHON_IP` is not set there. Please recheck the issue.

**Comment by singhpratyush** [comment]
@iiitv/odyssy-website: Is anyone else facing this issue?

**Comment by Prakash2403** [comment]
@singhpratyush I just printed value of DEBUG variable, it is showing True. Yet, if I remove the line to include `127.0.0.1` from ALLOWED_HOSTS, I get `DisallowedHost` exception.
