### ISSUE TITLE
Create app for tags

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#15]
The app would be used to create tags for pictures and news.

### Features
* Verification for validity - should be `^[a-zA-Z0-9][a-zA-Z0-9\-]{3,}$`
* Views
  * `/tag/<tag>/`
  * `/tag/<tag>/pictures`
  * `/tag/<tag>/news`
  * `/tag/<tag>/announcement`

**Comment by yashLadha** [comment]
The manytomany field should also be included in annpuncement, news and events too. As each such thing can have tags associated to them. So should i make model changes there too.

**Comment by singhpratyush** [comment]
Yes, you will require modifying those models too.

**Comment by yashLadha** [comment]
@singhpratyush  can u explain more about this regex `[a-zA-Z0-9][a-zA-Z0-9\-]{3,}`

**Comment by singhpratyush** [comment]
```
[a-zA-Z0-9]       - Starts with a-z or A-Z or 0-9
[a-zA-Z0-9\-]{3,} - May contain a-z or A-Z or 0-9 or - (literally) 3 or more number of times.
```

**Comment by yashLadha** [comment]
Is it at least 3

**Comment by singhpratyush** [comment]
Yes.

**Comment by yashLadha** [comment]
Why to have an extra regex `[a-zA-Z0-9]`?

**Comment by singhpratyush** [comment]
Because tag shouldn't start with `-`.

**Comment by yashLadha** [comment]
Sir {3,} is showing error . Saying `is not a valid regular expression: multiple repeat`

**Comment by singhpratyush** [comment]
Check this - https://regex101.com/r/f7VnMS/1

**Comment by yashLadha** [comment]
What should be done with the link `\<tag>\` ?

**Comment by singhpratyush** [comment]
Maybe show most used tags?

**Comment by yashLadha** [comment]
here we passed a  designated tag-name. So how will it be relevant to show most used tags.

**Comment by singhpratyush** [comment]
Oh! You were talking about `/tag/<tag>/` (I thought it is `/tag/` because of the way you mentioned it there).

In that section, show the latest n news, announcement and pictures related to that tag.
