### ISSUE TITLE
Warning while migrating Event app

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#19]
Event app gives `RuntimeWarning` while migrating database - 
```python
/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Event.end_time received a naive datetime (2017-05-23 23:29:02.266570) while time zone support is active.
  RuntimeWarning)
/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Event.end_time received a naive datetime (2017-05-23 23:29:36.181164) while time zone support is active.
  RuntimeWarning)
/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Event.start_time received a naive datetime (2017-05-23 23:29:02.266532) while time zone support is active.
  RuntimeWarning)
/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Event.start_time received a naive datetime (2017-05-23 23:29:36.181126) while time zone support is active.
  RuntimeWarning)
```

**Comment by Monal5031** [comment]
I tried migrating it on my pc, it worked :confused:

**Comment by Prakash2403** [comment]
@singhpratyush Sir, I tried some ways to solve this problem, but none of them worked. However, as long as our timezone is set as `Asia/Kolkata`, no problems will be there.

**Comment by singhpratyush** [comment]
The problem is [here](https://github.com/iiitv/Odyssy/blob/master/wsgi/odyssy/events/models.py#L12).

Try changing it to 
```python
from django.utils import timezone
...
start_time = models.DateTimeField(default=timezone.now())
...
```

**Comment by Prakash2403** [comment]
I have done that. But, still it is not timezone aware. Runtime Warning still says that database received a naive datetime object. I have read the documentation, but no help. There is a method `timezone.make_aware()` which is used to convert naive datetime object to aware datetime object explicitly, but it produces a runtime exception that `tz_info not found in datetime object`. I am unable to resolve this issue.
