### ISSUE TITLE
Create app for announcements

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#2]
This app would be used to manage announcements on the website.

### Features
* Ability to add display start time.
* Ability to add display end time.
* Content with HTML support.
* Views
  * Paginated list at `/announcement/`
  * Single announcement at `/announcement/<id>/`

Also, show all active announcements on the index page.

**Comment by yashLadha** [comment]
Do i make separate fields for title and description of announcement

**Comment by singhpratyush** [comment]
Yes.

**Comment by yashLadha** [comment]
What is the idea of start time and end time? Is it the period of announcement or something?

**Comment by singhpratyush** [comment]
Yes, it is the period for which announcement stays on the website.

**Comment by yashLadha** [comment]
Write to create post is on the site or i admin console.

**Comment by Monal5031** [comment]
I think it should be in admin console.

**Comment by yashLadha** [comment]
If it is in admin console. Them it won't give privacy to individual participants in it. As one party announcement should not be seen by other party announcement

**Comment by Monal5031** [comment]
What I'm thinking is if we add it in admin console then everyone who has to make an announcement will just to have to contact the admin or superusers.

**Comment by yashLadha** [comment]
But we are also giving individual access to participants or not?

**Comment by singhpratyush** [comment]
I am a bit confused here. Who is a **participant**?

**Comment by yashLadha** [comment]
Faculty or administrative body

**Comment by singhpratyush** [comment]
The announcements will be created from the admin panel. We can later configure the who-can-edit-what part or add a different interface if needed.

**Comment by yashLadha** [comment]
Ok sir.
