### ISSUE TITLE
Description in event app doesn't supports HTML

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#20]
Example description - 
```
This is an awesome event. Get tickets <a href="/">here</a>.
```

**Comment by Prakash2403** [comment]
@singhpratyush This feature wasn't mentioned as requirement in #5 .

**Comment by singhpratyush** [comment]
Yes, I missed it there. But it would be easier to tackle smaller issues like this one now.

Hope you aren't mad about it :sweat_smile:.

**Comment by Prakash2403** [comment]
Why to be mad, Sir :smile: ? I will fix it ASAP.

**Comment by singhpratyush** [comment]
Great! Assigned.
