### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#22]
This would help us in maintaining code quality and ensuring stability.

**Comment by Monal5031** [comment]
I can work on this but I'm confused on what to add in `before_script:`  and `script:`

**Comment by singhpratyush** [comment]
In `before_script` section, you may create database and users and in the `script` section, you may run the tests (but there are not any yet), etc.

Use `env` section to set up environment variables.

**Comment by Monal5031** [comment]
Ok I'll like to give it a try. 😅
