### ISSUE TITLE
Description of event app says "at" even when no location is given

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#24]
> Test Event 3 on 24 - May - 2017 at

**Comment by Prakash2403** [comment]
Can you mention the URL @singhpratyush Sir?

**Comment by singhpratyush** [comment]
https://odyssy.singhpratyush.in/

**Comment by Prakash2403** [comment]
It is not showing on my machine. I can post screenshot if you want

**Comment by Prakash2403** [comment]
@singhpratyush Issue fixed sir, please review.
