### ISSUE TITLE
Announcements appear at index even after they have expired

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#26]
e.g. - `Test announcement 1` at https://odyssy.singhpratyush.in/

**Comment by Monal5031** [comment]
@singhpratyush `Test announcement 1` is not there, instead it is showing `No latest announcement.`

**Comment by singhpratyush** [comment]
:+1: It was earlier there after end time (or maybe not). @Monal5031 can you please verify it locally.

**Comment by Monal5031** [comment]
@singhpratyush Tested it locally, the announcement still appears even after its end time.

**Comment by yashLadha** [comment]
@Monal5031  Have u check on index page or on the announcement page

**Comment by Monal5031** [comment]
@yashLadha Index page in basic app

**Comment by yashLadha** [comment]
But on my machine is not showing.

**Comment by yashLadha** [comment]
I tested it again. If the time and date (finDate) is less than current time and date it is showing no announcement.

**Comment by yashLadha** [comment]
Ohh i was only comparing date sending the fix for this.

**Comment by Monal5031** [comment]
@yashLadha News and Events app also have this bug.

**Comment by singhpratyush** [comment]
Events are okay. Please create an issue for news.

**Comment by Monal5031** [comment]
@singhpratyush Can you please retest the events app? Because in my system it still appears after expiry.
