### ISSUE TITLE
Make default time for announcement as current day

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#27]
As of now, the default date and time for start of announcement is `now` and default end time is undefined. Make the default time as start of this date (`dd-mm-yyyy 00:00:00+XYZ`) and end as `dd-mm-yyyy 23:59:59+XYZ`.

**Comment by yashLadha** [comment]
Sir it is already implemented as `default=datetime.datetime.now` runs every time somentry is saved. And not that it takes the default as the value when it migrated.

**Comment by singhpratyush** [comment]
> Make the default time as start of this date (`dd-mm-yyyy 00:00:00+XYZ`) and end as `dd-mm-yyyy 23:59:59+XYZ`.

**Comment by yashLadha** [comment]
Oh I got it sir. Sending Patch for this

**Comment by yashLadha** [comment]
Sir date for end time is current date or something else

**Comment by singhpratyush** [comment]
The end is the current date. I said it's undefined by default, just need to set a default value.
