### ISSUE TITLE
Bold tag has no effect on website

### ISSUE THREAD

**Issue by Monal5031** [iiitv/Odyssy#28]
The bold tag `<b>news</b>`at https://odyssy.singhpratyush.in/news/1/  is not showing any effect.
Edit: It is because `&lt;b&gt;news&lt;/b&gt;` is used in place of `<b>news</b>`

**Comment by Prakash2403** [comment]
HTML support is not added in single_news.html . To add it, just replace `info.description` with `info.description | safe`

**Comment by Monal5031** [comment]
Assign me this one.
