### ISSUE TITLE
Create app for news

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#3]
Depends on #2.
This app would be used to manage news on the website.

### Features
* Extends announcements
* Ability to add display start time.
* Content with HTML support.
* News body with HTML support.
* Views
  * Paginated list at `/news/`
  * Single view at `/news/<id>/`

Also, show latest 3 (should be configurable) news at index.

**Comment by Monal5031** [comment]
I would like to work on this one.

**Comment by Monal5031** [comment]
Please assign me to this.
