### ISSUE TITLE
What about past events?

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/Odyssy#34]
Events app displays the information about the upcoming events, shouldn't it be modified to also display information of past events with related news and photos.

Please take a look:  https://www.iiitb.ac.in/

**Comment by Prakash2403** [comment]
> Events app displays the information about the upcoming events, shouldn't it be modified to also display information of past events

Event app displays about every event. 

> with related news and photos.
HTML support is there in event description. We can easily`create a reference to related news and photos.
