### ISSUE TITLE
Create carousel upload portal

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#4]
Add it in the basic app and link to the admin panel. The user should be able to upload a list of images and also select the ones that will be actively shown at index.

Also add field for short description which may be utilised later.

**Comment by Prakash2403** [comment]
I would like to work on this issue.

**Comment by singhpratyush** [comment]
@Prakash2403: Assigned. You may add an app and set all required features in it. Also, you can set a `BooleanField` to keep track of active carousel images.

**Comment by Prakash2403** [comment]
@singhpratyush Sir, where to store uploaded image?

**Comment by singhpratyush** [comment]
https://github.com/jdriscoll/django-photologue
