### ISSUE TITLE
Create app for events

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#5]
### Features
* Name
* Start and End time
* Description
* Place
* Views
  * Paginated list at `/event/`
  * Single view at `/event/<id>`

Display latest 3 (should be configurable) events on the index page.

**Comment by Prakash2403** [comment]
I would like to work on it.

**Comment by Prakash2403** [comment]
@singhpratyush Shouldn't there be a field for event name?

**Comment by singhpratyush** [comment]
Yes there should be. I totally missed it. My bad :sweat_smile:.
