### ISSUE TITLE
Carousel can't be controlled using arrow keys

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#52]

**Comment by aashutoshrathi** [comment]
The arrow keys are working only if the slider is focused. i.e. Arrow key are working after you interact with carousel

**Comment by singhpratyush** [comment]
Should that be happening? I think that desired effect should be being able to scroll the carousel soon as we open the website.

**Comment by aashutoshrathi** [comment]
No, that doesn't happen by default as the focus is not on carousel, but we can force that by capturing the keydown event on the input control and giving conditions on keystrokes of left arrow(key 37) and right arrow (key 39)

**Comment by Anshuman-Verma** [comment]
Probably we can have carousel focused by  default on page load ?
