### ISSUE TITLE
Irrelevant social media links at footer

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#55]
It says Twitter, FB and LinkedIn while we do not have them.

**Comment by Monal5031** [comment]
@singhpratyush There is a fb page I think but its not official I guess.

**Comment by singhpratyush** [comment]
This github org is also not official.

**Comment by aashutoshrathi** [comment]
So are we going to remove them all ?

**Comment by Monal5031** [comment]
No only the twitter fb and linkedin I guess

**Comment by Anshuman-Verma** [comment]
Any assignees ?

**Comment by Monal5031** [comment]
@singhpratyush Please assign me this one.

**Comment by Monal5031** [comment]
@singhpratyush Please assign me this one.
