### ISSUE TITLE
Add original theme to current website

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#6]
Depends on #2 #3 #4 #5.
Add the original theme to current website, integrating data from all the apps.

There should be a global header/footer, which can be edited from a single file.

**Comment by Monal5031** [comment]
Does this has to be done in basic app?

**Comment by Monal5031** [comment]
@singhpratyush Please clarify my doubt.

**Comment by singhpratyush** [comment]
Yes, add this as a view in `basic`.

**Comment by Monal5031** [comment]
Please assign me this one.
Also, should I start with this one now or after #13 is merged?
