### ISSUE TITLE
Add "Contact Us" Page

### ISSUE THREAD

**Issue by geekyJock8** [iiitv/Odyssy#62]
This page will contain all the contact details of college(i.e. Address, Phone No., Map, Email Id).

**Comment by DipanshKhandelwal** [comment]
Assign it to me.

**Comment by yashLadha** [comment]
@DipanshKhandelwal GFT

**Comment by Monal5031** [comment]
@yashLadha sir this isn't decided yet. I mean the details, where it will be placed etc. Should we do this then?
