### ISSUE TITLE
NoReverseMatch at /adminphotologue/photo/

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/Odyssy#66]
Facing `u'photologue' is not a registered namespace` error while accessing https://odyssy.singhpratyush.in/adminphotologue/photo/ .
 Photos can be added by `add` button but unable to access all photos page in `adminphotologue` section.

**Comment by Prakash2403** [comment]
@mohitkyadav Thanks for pointing out the bug. It was working few days ago, but I think someone messed up with `urls.py` file. Just add `url(r'^photologue/', include('photologue.urls', namespace='photologue'))` in `odyssy/urls.py` and it will work. I will send a patch ASAP.
