### ISSUE TITLE
Make footer Sticky

### ISSUE THREAD

**Issue by ansarimofid** [iiitv/Odyssy#68]
The footer is not sticky and a lot of space is left at the bottom when the content is less. Try to make footer sticky to get rid of this problem.
Helpful Link:  [https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/).

Mobile Screenshot of the site
![odyssy singhpratyush in- galaxy s5](https://user-images.githubusercontent.com/9111119/27010775-495bc71e-4eca-11e7-83d2-3b5c44782d06.png)

**Comment by Monal5031** [comment]
Fixed in #86

**Comment by Monal5031** [comment]
Fixed in #89
