### ISSUE TITLE
Create app for People

### ISSUE THREAD

**Issue by Monal5031** [iiitv/Odyssy#80]
This app would be used to display items under nav-bar item `People`

### Features:
Following views are to be added at `people`
* Faculty (All faculties at `people/faculty/`)
    * Individual information at `people/faculty/faculty-name/ `
* Visiting Faculty (All visiting faculties at `people/visiting-faculty/`)
    * Individual information at `people/visiting-faculty/visiting-faculty-name/`
* Staff

There should be a option to add or remove new member.

**Comment by mohitkyadav** [comment]
Please assign me on this issue.

**Comment by Monal5031** [comment]
Each faculty should have this fields according to me:
Name
Academic qualifications
College of qualification
Year of qualification
Area of interest
Contact email

I'm not sure how can we add other details as every faculty doesn't have all the fields.
Views? @singhpratyush @yashLadha @Prakash2403 @mohitkyadav @geekyJock8

**Comment by mohitkyadav** [comment]
I think LinkedIn profile can be attached (if they have).
>I'm not sure how can we add other details (Publications & Presentations, Member of Professional bodies, etc) as every faculty doesn't have all the fields.
Only display (if any).

**Comment by Prakash2403** [comment]
> I'm not sure how can we add other details (Publications & Presentations, Member of Professional bodies, etc) as every faculty doesn't have all the fields.

We can keep the fields in our model and set `blank=True` and `null=True`.

**Comment by Monal5031** [comment]
Well I guess we can do that. Thanks @Prakash2403 sir
